#!/usr/bin/env sh
exec guile -s "$0" "$@"
!#

(use-modules (mud-lab))

(define player (make-player "player"))

(define bible
  (lambda (x)
    (cond ((eq? x 'name) "bible")
          ((eq? x 'name-with-article) "a bible")
          ((eq? x 'read)
           (display "I made haste, and delayed not to keep thy commandments.
		-- Psalms 119:60
")))))

(define lotr
  (lambda (x)
    (cond ((eq? x 'name) "lotr")
          ((eq? x 'name-with-article) "the Lord of the Rings (lotr)")
          ((eq? x 'read)
           (display "It is a dangerous business, Frodo, stepping out of your
front door.\n")))))

(define bus-stop (make-room "bus stop"
                            "A bus stop. The sign says that the next bus will come exactly five minutes before the rapture. The last one apparently took the dinosaurs away. All of them."
                            (cons -1 1)
                            (list "north")))

(define parliament (make-room "parliament"
                              "The parliament. You smell the smell of corruption and evil."
                              (cons 1 1)
                              (list "south")))

(define loo (make-room "loo"
                       "The loo."
                       (cons 1 0)
                       (list "south")))

(loo 'add-object lotr)

(define bar (make-room "bar"
                       "A bar. Do you want a whisky?"
                       (cons 0 0)
                       (list "north" "east")))

(bar 'add-object bible)

(define street (make-room "street"
                          "A deserted lonely depressing street. It rains."
                          (cons 0 1)
                          (list "west" "north" "south")))

(define rooms (list bus-stop parliament loo bar street))

;;;(game player rooms)
