(hall-description
  (name "mud-lab")
  (prefix "guile")
  (version "0.1")
  (author "Silas Vedder")
  (copyright (2020))
  (synopsis "")
  (description "")
  (home-page "")
  (license gpl3+)
  (dependencies `())
  (files (libraries
           ((scheme-file "mud-lab")
            (directory "mud-lab" ())))
         (tests ((directory
                   "tests"
                   ((test-result-file "simple-test")
                    (log-file "simple-test")
                    (scheme-file "simple-test")))))
         (programs ((directory "scripts" ())))
         (documentation
           ((org-file "README")
            (symlink "README" "README.org")
            (text-file "HACKING")
            (text-file "COPYING")
            (directory
              "doc"
              ((info-file "guile-mud-lab")
               (text-file ".dirstamp")
               (text-file "stamp-vti")
               (texi-file "mud-lab")
               (texi-file "version")))
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")
            (text-file "NEWS")
            (text-file "AUTHORS")
            (text-file "ChangeLog")))
         (infrastructure
           ((scheme-file "guix")
            (scheme-file "hall")
            (directory
              "build-aux"
              ((tex-file "texinfo")
               (text-file "mdate-sh")
               (scheme-file "test-driver")
               (text-file "missing")
               (text-file "install-sh")))
            (autoconf-file "configure")
            (automake-file "Makefile")
            (in-file "pre-inst-env")
            (directory
              "build-aux"
              ((tex-file "texinfo")
               (text-file "mdate-sh")
               (scheme-file "test-driver")
               (text-file "missing")
               (text-file "install-sh")))
            (autoconf-file "configure")
            (automake-file "Makefile")
            (in-file "pre-inst-env")
            (directory
              "build-aux"
              ((tex-file "texinfo")
               (text-file "mdate-sh")
               (scheme-file "test-driver")
               (text-file "missing")
               (text-file "install-sh")))
            (autoconf-file "configure")
            (automake-file "Makefile")
            (in-file "pre-inst-env")
            (directory
              "build-aux"
              ((tex-file "texinfo")
               (text-file "mdate-sh")
               (scheme-file "test-driver")
               (text-file "missing")
               (text-file "install-sh")))
            (autoconf-file "configure")
            (automake-file "Makefile")
            (in-file "pre-inst-env")
            (directory
              "build-aux"
              ((tex-file "texinfo")
               (text-file "mdate-sh")
               (scheme-file "test-driver")
               (text-file "missing")
               (text-file "install-sh")))
            (autoconf-file "configure")
            (automake-file "Makefile")
            (in-file "pre-inst-env")
            (directory
              "build-aux"
              ((tex-file "texinfo")
               (text-file "mdate-sh")
               (scheme-file "test-driver")
               (text-file "missing")
               (text-file "install-sh")))
            (autoconf-file "configure")
            (automake-file "Makefile")
            (in-file "pre-inst-env")))))
